# Basic Configuration
# baseurl = "https://lucho8908.github.io/"
languageCode = "en"

title = "Luis G. Polanco"
theme = "hyde-hyde"

## Hugo Built-in Features
# disqusShortname = "your-disqus-shortname"
# googleAnalytics = "your-google-analytics-id"
# enableRobotsTXT = true

# summarylength = 30

#paginate = 5

## Site Settings
[params]
    author = "Luis G. Polanco Contreras"
    title = "Luis G. Polanco Contreras"
    description = "I'm a PhD student at CMSE - MSU"
    authorimage = "/img/avatar.jpg"
    dateformat = "Jan 2, 2006"

    # sidebar, copyright & license
    #logoimage = "/img/hugo.png"
    #copyright = "htr3n"
    since = 2019
    license = "CC BY-SA 4.0"
    licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
    showBuiltWith = true

    # https://highlightjs.org
    highlightjs = true
    highlightjsstyle = "github"
   
    # please choose either GraphComment or Disqus or Utterances
    #GraphCommentId = "..."
    #UtterancesRepo = "..." # https://utteranc.es/
    #UtterancesIssueTerm = "..." # pathname, url, title, og:title
    #UtterancesTheme = "..." # github-light or github-dark

    # Table of contents
    #toc = none, "hugo", or "tocbot"

## Social Accounts
[params.social]
    github = "lucho8908"
    #instagram = "<username>"
    #xing = "<username>"
    linkedin = "luis-polanco-29b519131"
    #twitter = "<username>"
    #facebook = "<username>"
    #microblog = "<username>"
    #stackoverflow = "<username>"
    #telegram = "<username>"
    # orcid = "<xxxx-xxxx-xxxx-xxxx>"
    email = "polanco2@msu.edu"
    # gravatar = "your-email@example.com"
    # pgpkey = "<path-to-your-key-in-/static>"

## Main Menu
# [[menu.main]]
#     name = "Posts"
#     weight = 100
#     identifier = "posts"
#     url = "/posts/"
# [[menu.main]]
#     name = "Portfolio"
#     identifier = "portfolio"
#     weight = 200
#     url = "/portfolio/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 100
    url = "/about/"

[[menu.main]]
    name = "Publications"
    identifier = "Publications"
    weight = 200
    url = "/publications/"

[[menu.main]]
    name = "Teaching"
    identifier = "Teaching"
    weight = 300
    url = "/teaching/"

[[menu.main]]
    name = "CV"
    identifier = "CV"
    weight = 400
    url = "../pdfs/Resume_Luis_Polanco.pdf"

[[menu.main]]
    name = "Random"
    identifier = "random"
    weight = 500
    url = "/random/"
